### ISSUE TITLE
Cut a new release for Web3j-OpenAPI

### ISSUE THREAD

**Issue by rach-id** [hyperledger/web3j-openapi#100]
As per the discussion under https://github.com/web3j/web3j-openapi/issues/99, the current openapi generated project is not using the latest version of sokt.
Thus, we will need to cut a new release of the library, using the latest sokt and web3j versions, to support the latest solidity versions.

**Comment by NickSneo** [comment]
Released web3j open-api 4.12.2 - https://github.com/hyperledger/web3j-openapi/releases/tag/v4.12.2
